stages:
  - validate
  - secret-scan
  - sast
  - config-scan
  - build-image
  - sbom
  - image-scan
  - deploy
  - verify
  
variables:
  NAMESPACE: "demo"
  APP_NAME: "demo-nginx"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

build-image:
  stage: build-image
  script:
    - echo "CI_REGISTRY=$CI_REGISTRY"
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
    - test -n "$CI_REGISTRY" || (echo "CI_REGISTRY is empty. GitLab Container Registry may not be enabled." && exit 1)
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  only:
    - main

trivy_image_scan:
   stage: scan
   script:
     - docker load -i image.tar
     - trivy image --skip-version-check --skip-java-db-update --severity HIGH,CRITICAL --format json --output trivy-image-report.json   
      vulnerable-app:$CI_COMMIT_SHORT_SHA

artifacts:
   when: always
   paths:
   - trivy-image-report.json
   expire_in: 1 week

trivy_image_scan:
  stage: scan
  script:
    - docker load -i image.tar
    - trivy image --skip-version-check --skip-java-db-update --severity HIGH,CRITICAL --format json --output trivy-image-report.json   
      vulnerable-app:$CI_COMMIT_SHORT_SHA
  artifacts:
    when: always
    paths:
      - trivy-image-report.json
    expire_in: 1 week
  allow_failure: false
  only:
    - main

generate-sbom:
  stage: sbom
  script:
    - syft "$IMAGE_NAME" -o cyclonedx-json=sbom-cyclonedx.json
  artifacts:
    when: always
    paths:
      - sbom-cyclonedx.json
    expire_in: 7 days
  only:
    - main

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:1.30
    entrypoint: [""]
  script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl apply -f k8s/
    - kubectl rollout status deployment/$APP_NAME -n $NAMESPACE
  only:
    - main

verify:
  stage: verify
  image:
    name: bitnami/kubectl:1.30
    entrypoint: [""]
  script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl get namespace $NAMESPACE
    - kubectl get deployment $APP_NAME -n $NAMESPACE
    - kubectl get pods -n $NAMESPACE -o wide
    - kubectl get svc -n $NAMESPACE
  only:
    - main
