stages:
  - validate
  - secret-scan
  - sast
  - config-scan
  - image-scan
  - deploy
  - verify

variables:
  NAMESPACE: "demo"
  APP_NAME: "demo-nginx"
  IMAGE_NAME: nginx:1.28.0-alpine

validate-k8s:
  stage: validate
  script:
    - test -n "$KUBECONFIG_B64" || (echo "KUBECONFIG_B64 is not available" && exit 1)
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl config current-context
    - kubectl apply --dry-run=client -f k8s/

secret-scan:
  stage: secret-scan
  image:
    name: zricethezav/gitleaks:v8.18.4
    entrypoint: [""]
  script:
    - gitleaks detect --source . --verbose --redact --report-format json --report-path gitleaks-report.json
  artifacts:
    when: always
    paths:
      - gitleaks-report.json
    expire_in: 7 days
  allow_failure: false

sast:
  stage: sast
  image: returntocorp/semgrep:1.75.0
  script:
    - semgrep scan --config auto --json --output semgrep-report.json .
  artifacts:
    when: always
    paths:
      - semgrep-report.json
    expire_in: 7 days
  allow_failure: false

config-scan:
  stage: config-scan
  image:
    name: aquasec/trivy:0.52.2
    entrypoint: [""]
  script:
    - trivy config --exit-code 1 --severity HIGH,CRITICAL --format json --output trivy-config-report.json k8s/
  artifacts:
    when: always
    paths:
      - trivy-config-report.json
    expire_in: 7 days
  allow_failure: false

image-scan:
  stage: image-scan
  script:
    - trivy image --scanners vuln --pkg-types os --skip-java-db-update --skip-version-check --severity CRITICAL --format table "$IMAGE_NAME"
    - trivy image --scanners vuln --pkg-types os --skip-java-db-update --skip-version-check --exit-code 1 --severity CRITICAL --format json --output   
      trivy-image-report.json "$IMAGE_NAME"
  artifacts:
    when: always
    paths:
      - trivy-image-report.json
    expire_in: 7 days
  allow_failure: false

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:1.30
    entrypoint: [""]
  script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl apply -f k8s/
    - kubectl rollout status deployment/$APP_NAME -n $NAMESPACE
  only:
    - main

verify:
  stage: verify
  image:
    name: bitnami/kubectl:1.30
    entrypoint: [""]
  script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_B64" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl get namespace $NAMESPACE
    - kubectl get deployment $APP_NAME -n $NAMESPACE
    - kubectl get pods -n $NAMESPACE -o wide
    - kubectl get svc -n $NAMESPACE
  only:
    - main
